import './globals.css'
import Footer from "../Components/Footer.jsx";
import Navbar from '../Components/Nav.jsx';



export const metadata = {
  title: "NEXT_TEST",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>

        <Navbar />
        {children} 
        <Footer />
      </body>

    </html>
  );
}
